name: Build AppImage AMD64 (Reusable)

on:
  workflow_call:
    inputs:
      build_flags:
        description: 'Flags to pass to build.sh (e.g., "--clean no")'
        required: false
        type: string
        default: ''

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install FUSE for AppImageTool
        run: |
          sudo apt-get update
          sudo apt-get install -y libfuse2
      - name: Make build script executable
        run: chmod +x ./build.sh
      - name: Run build script
        run: |
          echo "Running AMD64 build with flags: ${{ inputs.build_flags }}"
          ./build.sh ${{ inputs.build_flags }}
      - name: Upload AMD64 Artifact
        uses: actions/upload-artifact@v4
        with:
          name: appimage-amd64
          path: claude-desktop-*.AppImage
          if-no-files-found: error
