name: CI

on:
  push:
    branches: [main, dev]
    paths:
      - 'build.sh'
      - 'scripts/**'
      - '.github/workflows/**'
    tags:
      - 'v*'
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build-amd64:
    uses: ./.github/workflows/build-amd64.yml
    with:
      build_flags: ''

  build-arm64:
    uses: ./.github/workflows/build-arm64.yml
    with:
      build_flags: ''

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [build-amd64, build-arm64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download AMD64 AppImage artifact
        uses: actions/download-artifact@v4
        with:
          name: appimage-amd64
          path: artifacts/
      - name: Download ARM64 AppImage artifact
        uses: actions/download-artifact@v4
        with:
          name: appimage-arm64
          path: artifacts/
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          files: artifacts/**/*.AppImage
